name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x
            9.x
            10.x

      - name: Create Template Package
        run: |
          dotnet pack -c Release

      - name: Install Template Package
        run: |
          dotnet new install bin/Release/Dimodi.Telerik.Project.Templates.6.3.0.nupkg

      - name: Run Tests
        run: sh tests.sh
